server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true


spring:
  output:
    ansi:
      enabled: always
  # datasource:
  #   url: jdbc:mysql://localhost:3306/paging_searching?serverTimezone=Asia/Seoul
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: root
  #   password: 1234
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations:
        - classpath:db/data.sql

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    #      ddl-auto: update
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true


logging:
  level: # TRACE > DEBUG > INFO > WARN > ERROR
    com.example.demo.module: debug
